---
#-------------------------------
# General Site Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://castroforgeorgia.com" # the base hostname & protocol for your site, e.g. http://example.com

# Repository settings for GitHub metadata
repository: CastroForGeorgia/GA-5

# Collections directory
collections_dir: content

# Polyglot configuration
languages: ["en", "es", "vi", "ko"]
default_lang: "en"
exclude_from_localization:
  ["javascript", "js", "images", "css", "assets", "feed.xml", "sitemap.xml"]
parallel_localization: true
lang_from_path: true

# Other
vite_dev_server_url: http://localhost:5173

#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title/
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-relative-links
  - jekyll-redirect-from
  - jekyll-polyglot

paginate: 7
paginate_path: "/blog/page/:num"

#-------------------------------
# Collections
collections:
  pages:
    output: true
    permalink: /:name/
  posts:
    output: true
    permalink: /blog/:slug/
  projects:
    output: true
    permalink: /project/:slug/
  policies:
    output: true
    permalink: /policy/:slug/
  sections:
    output: false # Sections are included, not standalone pages
  faqs:
    output: true
    permalink: /faq/:slug/
  testimonials:
    output: false # Testimonials are included, not standalone pages
  # Campaign collection
  campaign:
    output: true
    permalink: /campaign-docs/:path/

# Pages Path
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "content/_pages"
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "content/_posts"
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "content/_projects"
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: "content/_policies"
      type: "policies"
    values:
      layout: "policy"
  - scope:
      path: "content/_sections"
      type: "sections"
    values:
      layout: "section"
  - scope:
      path: "content/_faqs"
      type: "faqs"
    values:
      layout: "faq"
  - scope:
      path: "content/_testimonials"
      type: "testimonials"
    values:
      layout: "testimonial"
  # Campaign collection default
  - scope:
      path: "content/_campaign"
      type: "campaign"
    values:
      layout: "page"
  - scope:
      path: "content/_campaign/welcome-hub"
      type: "campaign"
    values:
      layout: "welcome-hub"
  # Neighborhoods collection defaults
  - scope:
      path: "content/_campaign/neighborhoods"
      type: "campaign"
    values:
      layout: "neighborhoods"

sass:
  sass_dir: _sass
  style: compressed

# Asset paths
assets:
  images: assets/images
  js: assets/js
  css: assets/css

relative_links:
  enabled: true
  collections: true

# Include Vite build output in Jekyll processing
include:
  - assets/dist
