#-------------------------------
# Site Settings
title: CastroForGeorgia
logo: 'logo.png' # Only the filename
logo_dark: 'logo.png'
description: Andres Castro, a champion for the people in Georgia's 5th Congressional District. 
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: "Donate"
      url: 'https://secure.actblue.com/donate/castroforgeorgia'
    - title: "Why I'm Running"
      url: '/blog/why-im-running/'
    - title: 'Contact'
      url: '/contact/'
    - title: 'Economy'
      url: '/policy/economy/'
    - title: 'Healthcare'
      url: '/policy/healthcare/'
    - title: 'Housing'
      url: '/policy/housing-community/'



#-------------------------------
# Author Settings
author:
  author_name: Andres Castro
  author_avatar: 'about-me-photo-zoom.jpg'


#-------------------------------
# Blog Section Settings
blog:
  blog_title: Blog
  blog_description: Let's build a future that works for all of us.

#-------------------------------
# Social Links
social:
- {icon: "fa-brands fa-instagram", name: "Instagram", link: "https://www.instagram.com/castroforgeorgia/"}
- {icon: "fa-brands fa-github", name: "Github", link: "https://github.com/CastroForGeorgia"}
- {icon: "fa-brands fa-bluesky", name: "Bluesky", link: "https://bsky.app/profile/castroforgeorgia.com"}
- {icon: "fa-brands fa-huggingface", name: "Huggingface", link: "https://huggingface.co/CastroForGeorgia"}

# Example of adding a new link to the footer - {icon: "fa-brands fa-mastodon", name: "Mastodon", link: "https://mastodon.social"}
# Other icons can be found at https://fontawesome.com/icons

#-------------------------------
# Google Analytics
google-analytics: G-SMVGY1JMQ1

#-------------------------------
# Localization Settings
languages:
  default: "en"
  supported:
  - lang_code: en
    lang_name: "English (US)"
  - lang_code: es
    lang_name: "Español (MX)"
  - lang_code: vi
    lang_name: "Vietnamese (VN)"
  - lang_code: ko
    lang_name: "Korean (KR)"
